name: Deploy Databricks Pipeline

on:
  push:
    branches:
      - main
    # paths:
    #   - "ML/main.py"
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: Dev   

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r ML/requirements.txt pytest

      - name: Run Tests
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        run: pytest ML/tests/

      - name: Run Deployment Script
        if: github.event_name== 'push'
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        run: python ML/main.py
